# Front door lights
- alias: 'Front door light on'
  initial_state: True
  trigger: 
  - platform: sun
    event: sunset
    offset: '-00:10:00'
  action:
  - service: light.turn_on
    entity_id: light.front_door
    
- alias: 'Front door light off'
  initial_state: True
  trigger:
  - platform: sun
    event: sunrise
    offset: '00:15:00'
  action:
  - service: light.turn_off
    entity_id: light.front_door

- alias: 'All lights off'
  initial_state: True
  trigger:
  - platform: sun
    event: sunrise
    offset: '00:15:00'
  action:
  - service: light.turn_off
    entity_id: group.all_lights

- alias: 'Living room lights - 4-5pm'
  initial_state: True
  trigger:
    platform: time
    at: '16:00:00'
  condition:
    - condition: template
      value_template: '{{states.sensor.family_room_motion_sensor.attributes.lx < 25}}'
  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Family room"
      scene_name: "Concentrate"

- alias: 'Living room lights - 5-6pm'
  initial_state: True
  trigger:
    platform: time
    at: '17:00:00'
  condition:
    - condition: template
      value_template: '{{states.sensor.family_room_motion_sensor.attributes.lx < 25}}'
  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Family room"
      scene_name: "Read"

- alias: 'Living room lights - 6-7pm'
  initial_state: True
  trigger:
    platform: time
    at: '18:00:00'
  condition:
    - condition: template
      value_template: '{{states.sensor.family_room_motion_sensor.attributes.lx < 25}}'
  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Family room"
      scene_name: "Relax"

- alias: 'Living room lights - 7-8pm'
  initial_state: True
  trigger:
    platform: time
    at: '19:00:00'
  condition:
    - condition: template
      value_template: '{{states.sensor.family_room_motion_sensor.attributes.lx < 25}}'
  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Family room"
      scene_name: "Dimmed"

- alias: 'Living room lights - 8-11pm'
  initial_state: True
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    - condition: template
      value_template: '{{states.sensor.family_room_motion_sensor.attributes.lx < 25}}'
  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Family room"
      scene_name: "9pm"

- alias: 'Living room lights - after 11pm'
  initial_state: True
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: light.turnoff
    entity_id: light.family_room
    
- alias: 'Living room lights - night light'
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.family_room_motion_sensor
    to: 'on'
  condition:
    - condition: time
      after: '23:00:00'
      before: '06:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: script.living_room_night_light