# Front door lights
- alias: 'Front door light on'
  trigger: 
  - platform: sun
    event: sunset
    offset: '-00:10:00'
  action:
  - service: light.turn_on
    entity_id: light.front_door
    
- alias: 'Front door light off'
  trigger:
  - platform: sun
    event: sunrise
    offset: '00:15:00'
  action:
  - service: light.turn_off
    entity_id: light.front_door
