homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_time_zone
  # Customization file
  customize: !include customize.yaml

frontend:

config:

updater:

discovery:

conversation:

history:

logbook:

map:

sun:

sensor:
  - platform: yr
  - platform: waze_travel_time
    origin: !secret waze_origin
    destination: !secret waze_destination
    region: !secret waze_region
  - platform: hue
    ip_address: !secret hue_ip_address
    token: !secret_hue_token

tts:
  - platform: google

cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

rachio:
  api_key: !secret rachio_api_key

panel_iframe:
  rachio:
    title: Rachio
    url: "https://app.rach.io"
    icon: mdi:water-pump
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret hass_url
